# Generated by Django 5.2.3 on 2025-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('General-Medicine', 'General Medicine'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology')], max_length=28)),
                ('doctor', models.CharField(choices=[('Dr. Smith', 'Dr. Smith'), ('Dr. Johnson', 'Dr. Johnson'), ('Dr. Williams', 'Dr. Williams'), ('Dr. Kyle', 'Dr. Kyle')], max_length=28)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
