# Generated by Django 5.2.3 on 2025-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_date', models.DateField()),
                ('doctor', models.CharField(choices=[('Dr. Smith', 'Dr. Smith'), ('Dr. Johnson', 'Dr. Johnson'), ('Dr. Williams', 'Dr. Williams'), ('Dr. Kyle', 'Dr. Kyle')], max_length=28)),
                ('diagnosis', models.CharField(max_length=100)),
                ('medication', models.TextField()),
                ('allergies', models.CharField(max_length=100)),
                ('treatment', models.TextField()),
            ],
        ),
    ]
