# Generated by Django 5.2.3 on 2025-06-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_medicaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldata',
            old_name='medication',
            new_name='medications',
        ),
    ]
