# Generated by Django 5.2.3 on 2025-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_medication_medicaldata_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
