# Generated by Django 5.2.3 on 2025-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appointment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
