# Generated by Django 5.2.3 on 2025-06-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0010_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister'),
        ),
    ]
