# Generated by Django 5.2.3 on 2025-06-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_medicaldata_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_prescribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('General-Medicine', 'General Medicine'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics')], max_length=28),
        ),
    ]
